### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by yozef** [olofmagnusson/healthkit-titanium-module#1]
This module looks interesting.... I wonder if a usage example is possible so we can know how to use it. Thx

**Comment by roelandp** [comment]
I'm also very much interested in this. Is it working for you?

**Comment by olofmagnusson** [comment]
Hi,
I've added some instructions.

**Comment by roelandp** [comment]
Very, very cool, thanks a great bunch! 

are you cofounding the shape race app? 

cheers, roeland

**Comment by olofmagnusson** [comment]
Nope, I just did the Healthkit integration.

**Comment by roelandp** [comment]
Hee Olof!

tried some more with integrating and rebuilding. The first function works fine, (isSupported())

however whenever trying to implement the readTypes / writeTypes by means of the vars you gave in the sample: 

var readTypes = ["HKQuantityTypeIdentifierStepCount",   "HKQuantityTypeIdentifierBodyMass"];
var writeTypes = ["HKQuantityTypeIdentifierBodyFatPercentage", "HKQuantityTypeIdentifierDietaryFatTotal"];
mod.authorize(writeTypes, readTypes, function(res){
it throws an error at: 

-[__NSArrayM objectForKey:]: unrecognized selector sent to instance 0x15f42bf0


Which in Xcode corresponds to the 'getTypes' nsDictionary... 

Am I doing something wrong here? 

Thanks for a little quick help, 

kind regards, Roeland

**Comment by olofmagnusson** [comment]
Sorry I gave the wrong format for the arrays (each type has to have its own array). This is the correct format:


 var writeTypes = {
        HKCategoryType: [],
        HKCharacteristicType : [],
        HKCorrelationType : [],
        HKQuantityType : ["HKQuantityTypeIdentifierStepCount", "HKQuantityTypeIdentifierActiveEnergyBurned"],
        HKWorkoutType: ["HKWorkoutType"]
};
 
 var readTypes = {
        HKCategoryType: [],
        HKCharacteristicType : [],
        HKCorrelationType : [],
        HKQuantityType : ["HKQuantityTypeIdentifierStepCount", "HKQuantityTypeIdentifierActiveEnergyBurned"],
        HKWorkoutType: ["HKWorkoutType"]
};

**Comment by roelandp** [comment]
Great thanks, also, I noticed that in order to get correct Startdate & Enddate tracking inside the Health app, one should add the 'zeropadding' to the hours - minutes - seconds, to your xcodeDate(d) function 

```
function addZero(i) {
    if (i < 10) {
        i = "0" + i;
    }
    return i;
}


function xcodeDate(d){
    return d.getFullYear() + "-" + (d.getMonth() + 1) + "-" + d.getDate() + " " + addZero(d.getHours()) + ":" + addZero(d.getMinutes()) + ":" + addZero(d.getSeconds());
}

```

Also I noticed a typo on r.370 of GyhShaperacehealthkitComModule.m @ _HKWorko**he**utActivityType_

    [HKWorkout workoutWithActivityType:[props objectForKey:@"HKWorkoheutActivityType"]

should be 

    [HKWorkout workoutWithActivityType:[props objectForKey:@"HKWorkoutActivityType"]


And I personally changed in the same file the following lines: 
r. 386 / r. 387

    startDate: intervals[0]
    endDate: intervals[1]];

into 

    startDate: [self NSDateFromCustomJavaScriptDateString:[props objectForKey:@"startDate"]]
    endDate: [self NSDateFromCustomJavaScriptDateString:[props objectForKey:@"endDate"]]];


I'm not sure I understand the lines about the interval and the -1200 dating, maybe it's specific for your app. 

Anyhow I got it running, really cool! 
Also managed to crash the Health app, by posting 'null' values to calories burned. This way you can actually crash the Health app itself :)

sorry I'm not really into pushing/ pulling otherwise i'd posted a pull request. 
Alright.

 Thanks again! 

cheers, roeland

**Comment by olofmagnusson** [comment]
Thanks. I will look into your suggestions.

**Comment by mawarnes** [comment]
NSDate dateWithTimeIntervalSinceNow: -1200 is a timestamp 2 minutes ago.
@"HKWorkoheutActivityType" is still a typo
